# -*- coding: utf-8 -*-
"""Twitter-Sentiment-Analysis-source.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/172xwn69KOH6DaK0ML4Fy48kihmZq_7ZB
"""

import pandas as pd

from imblearn.under_sampling import  RandomUnderSampler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Model
from sklearn.svm import SVC # Support Vector Machine

print('*** Twitter Sentiment Analyzer ***')
print('=================================== \n')
print('ML Model - Support Vector Machines \n \n')

# Load Dataset
df_tweet = pd.read_csv('Tweets.csv')
print('Twitter dataset loaded successfully..')

# Drop empty data
df = df_tweet.dropna(axis=0)
print('Removed Null valued rows')

# Resample data to remove data imbalance
random_us = RandomUnderSampler(random_state=0)
df, df['sentiment'] = random_us.fit_resample(df[['selected_text']], df['sentiment'])
print('Resampled Data')


X = df['selected_text']
y = df['sentiment']

print('Splitting Data into train and test')
# Splitting Data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


print('Vectorizing selected_text')
# Convert text data to numerical vector
vectorizer = TfidfVectorizer(stop_words='english')
# Train Data
X_train_vector = vectorizer.fit_transform(X_train)

# Test Data
X_test_vector = vectorizer.transform(X_test)

"""Support Vector Machines (SVM)"""

# Define Model
model_SVC = SVC(kernel='linear')

print('Model Training in progress....')
# Fit Model
model_SVC.fit(X_train_vector, y_train)

print('\n \n Predicting for X_test data')
# Predict
prediction_SVC = model_SVC.predict(X_test_vector)


print('Accuracy Score (%) :', accuracy_score(y_test, prediction_SVC)*100)

print('\n Classification Report')
print(classification_report(y_test, prediction_SVC))

# Infinite Loop until user close the terminal
i=0
while i<=10:
    text = input('\nEnter text : ')
    print('Model Prediction - ', model_SVC.predict(vectorizer.transform([text])))
